spring:
  application:
    name: springboot-jpa

  config:
    import: optional:file:.env

  jpa:
    hibernate:
      ddl-auto: update      # [none | validate | update | create | create-drop]
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        use-new-id-generator-mappings: true

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    serialization:
      fail-on-empty-beans: false

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 6000ms

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/api/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-authentication-method: post
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - name
              - email
            redirect-uri: "{baseUrl}/api/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-authentication-method: post
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - profile
              - account_email
            redirect-uri: "{baseUrl}/api/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  override-with-generic-response: false

logging:
  level:
    com.back: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

jwt:
  secret: ${JWT_SECRET:3f1e2a0e-8e8f-4c0a-9d3f-b3fae09e6d5a}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:PT15M}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:PT168H}

cookie:
  secure: false

app:
  base-url: ${BASE_URL:http://localhost:8080}

server:
  port: 8080

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}

tmdb:
  api:
    key: ${TMDB_API_KEY}

library:
  api-key: ${Library_API_KEY}