name: Backend CI
on:
  pull_request:
    branches:
      - dev
    paths:
      - 'backend/**'
jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - run: cd backend && ./gradlew clean build test --no-daemon
