name: Backend CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - dev
    paths:
      - 'backend/**'

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      LIBRARY_API_KEY: ${{ secrets.LIBRARY_API_KEY }}
      REDIS_HOST: localhost
      REDIS_PORT: 6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to gradlew
        working-directory: ./backend
        run: chmod +x ./gradlew

      - name: Build and test backend
        working-directory: ./backend
        run: ./gradlew clean build test --no-daemon
