version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "19:00"
    commit-message:
      prefix: "deps(frontend)"
    groups:
      all-frontend:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "19:00"
    commit-message:
      prefix: "deps(backend)"
    groups:
      all-backend:
        patterns:
          - "*"
